[build]
  command = "node scripts/netlify-build.js"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=8192"
  NEXT_TELEMETRY_DISABLED = "1"

# Build settings optimized for large static sites
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects from old URLs
[[redirects]]
  from = "/compensacion-laboral"
  to = "/es/areas-de-practica/compensacion-laboral"
  status = 301
  force = true

[[redirects]]
  from = "/defensa-criminal"
  to = "/es/areas-de-practica/defensa-criminal"
  status = 301
  force = true

[[redirects]]
  from = "/derecho-familia"
  to = "/es/areas-de-practica/derecho-familia"
  status = 301
  force = true

[[redirects]]
  from = "/inmigracion"
  to = "/es/areas-de-practica/inmigracion"
  status = 301
  force = true

[[redirects]]
  from = "/lesiones-personales"
  to = "/es/areas-de-practica/lesiones-personales"
  status = 301
  force = true

# Environment variables (you'll set these in Netlify UI)
[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://vasquezlawfirm.com"

# Plugin for Next.js (essential for static export)
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Forms handling (if needed)
[functions]
  directory = "netlify/functions"