// Mock for lucide-react icons
const MockIcon = () => null;

// Export all commonly used icons as the same mock component
module.exports = {
  __esModule: true,
  // Common icons used in the codebase
  ChevronDown: MockIcon,
  ChevronUp: MockIcon,
  ChevronLeft: MockIcon,
  ChevronRight: MockIcon,
  Check: MockIcon,
  X: MockIcon,
  Search: MockIcon,
  Menu: MockIcon,
  Close: MockIcon,
  ArrowRight: MockIcon,
  ArrowLeft: MockIcon,
  ArrowUp: MockIcon,
  ArrowDown: MockIcon,
  Star: MockIcon,
  Heart: MockIcon,
  User: MockIcon,
  Users: MockIcon,
  Mail: MockIcon,
  Phone: MockIcon,
  MapPin: MockIcon,
  Calendar: MockIcon,
  Clock: MockIcon,
  Info: MockIcon,
  AlertCircle: MockIcon,
  CheckCircle: MockIcon,
  XCircle: MockIcon,
  Plus: MockIcon,
  Minus: MockIcon,
  Edit: MockIcon,
  Trash: MockIcon,
  Settings: MockIcon,
  Home: MockIcon,
  Globe: MockIcon,
  Shield: MockIcon,
  Lock: MockIcon,
  Eye: MockIcon,
  EyeOff: MockIcon,
  FileText: MockIcon,
  Download: MockIcon,
  Upload: MockIcon,
  Loader: MockIcon,
  Spinner: MockIcon,
  // Default export for any missing icons
  default: MockIcon,
};
