#!/usr/bin/env tsx
import { Client } from 'pg';
import RssParser from 'rss-parser';
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables
dotenv.config({ path: path.join(process.cwd(), '.env') });
dotenv.config({ path: path.join(process.cwd(), '.env.local'), override: true });

async function createNewsBlog() {
  console.log('🚀 VLF News Blog Creator\n');

  const dbUrl = process.env.DATABASE_URL;
  if (!dbUrl) {
    console.error('❌ DATABASE_URL not found');
    return;
  }

  // Create direct PostgreSQL client
  const client = new Client({
    connectionString: dbUrl,
    ssl: {
      rejectUnauthorized: false,
    },
  });

  try {
    // Connect to database
    await client.connect();
    console.log('✅ Database connected');

    // Check blog post count
    const countResult = await client.query('SELECT COUNT(*) FROM "BlogPost"');
    console.log(`📊 Current blog posts: ${countResult.rows[0].count}`);

    // Fetch news from RSS
    console.log('\n📡 Fetching immigration news...');
    const parser = new RssParser({
      timeout: 10000,
      headers: {
        'User-Agent': 'Vasquez Law Firm News Monitor/1.0',
      },
    });

    const feed = await parser.parseURL(
      'https://www.federalregister.gov/api/v1/documents.rss?conditions[agencies][]=homeland-security-department'
    );

    if (!feed.items || feed.items.length === 0) {
      console.log('❌ No news items found');
      return;
    }

    console.log(`✅ Found ${feed.items.length} news items`);

    // Create blog post from first item
    const item = feed.items[0];
    console.log(`\n📝 Creating blog post: "${item.title}"`);

    // Generate content
    const title = `Immigration Update: ${item.title}`;
    const slug = generateSlug(title);
    const content = generateContent(item);
    const excerpt = (item.contentSnippet || item.summary || '').substring(0, 200) + '...';
    const pubDate = new Date(item.pubDate || Date.now());

    // Insert blog post
    const insertResult = await client.query(
      `INSERT INTO "BlogPost" (
        id, title, slug, content, excerpt, "metaDescription", "metaKeywords",
        category, status, "publishedAt", author, tags, keywords, metadata,
        seo, "createdAt", "updatedAt"
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW(), NOW()
      ) RETURNING id, slug`,
      [
        generateId(),
        title,
        slug,
        content,
        excerpt,
        excerpt.substring(0, 160),
        ['immigration', 'federal register', 'DHS', 'immigration law'],
        'immigration',
        'published',
        pubDate,
        'Vasquez Law Firm Legal Team',
        ['immigration', 'federal-register', 'dhs', 'news'],
        ['immigration law', 'DHS', 'federal register'],
        JSON.stringify({
          source: 'Federal Register - DHS',
          sourceUrl: item.link,
          originalTitle: item.title,
          autoGenerated: true,
          urgent: false,
        }),
        JSON.stringify({
          metaTitle: `${title} | Vasquez Law Firm`,
          metaDescription: excerpt.substring(0, 160),
          keywords: 'immigration law, DHS, federal register',
        }),
      ]
    );

    console.log('\n✅ Blog post created successfully!');
    console.log(`   ID: ${insertResult.rows[0].id}`);
    console.log(`   URL: /blog/${insertResult.rows[0].slug}`);

    // Show recent posts
    console.log('\n📰 Recent Immigration News Posts:');
    const recentPosts = await client.query(
      `SELECT title, slug, "publishedAt" FROM "BlogPost" 
       WHERE category = 'immigration' AND status = 'published'
       ORDER BY "publishedAt" DESC LIMIT 5`
    );

    recentPosts.rows.forEach((post, index) => {
      console.log(`${index + 1}. ${post.title.substring(0, 60)}...`);
      console.log(`   Date: ${new Date(post.publishedAt).toLocaleDateString()}`);
      console.log(`   URL: /blog/${post.slug}`);
    });

    console.log('\n✅ News monitoring system is working perfectly!');
    console.log('🎯 The blog agent can now use this database to create posts.');
  } catch (error) {
    console.error('❌ Error:', error);
  } finally {
    await client.end();
  }
}

function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function generateId(): string {
  return `clr${Date.now()}${Math.random().toString(36).substr(2, 9)}`;
}

function generateContent(item: any): string {
  return `
<article class="legal-update immigration-news">
  <div class="bg-gradient-to-r from-[#6B1F2E] to-[#8b2635] text-white p-8 rounded-lg mb-8 shadow-xl">
    <p class="text-[#C9974D] font-semibold uppercase tracking-wider mb-2">YO PELEO™ NOTICIAS - Immigration Law Update</p>
    <h1 class="text-4xl font-bold mb-4">${item.title}</h1>
    <div class="flex items-center space-x-4 text-sm opacity-90">
      <span>Source: Federal Register</span>
      <span>•</span>
      <span>Published: ${new Date(item.pubDate || Date.now()).toLocaleDateString()}</span>
    </div>
  </div>

  <div class="max-w-4xl mx-auto px-4">
    <div class="text-xl text-gray-700 mb-8 leading-relaxed">
      ${item.contentSnippet || item.summary || 'This update contains important information about recent immigration regulations.'}
    </div>

    <section class="mb-12">
      <h2 class="text-3xl font-bold text-[#6B1F2E] mb-6">What This Means for Immigrants</h2>
      <div class="bg-gray-50 p-6 rounded-lg">
        <p>This federal register update may affect your immigration case. Key areas of impact include processing times, 
        documentation requirements, and eligibility criteria. Stay informed about these changes.</p>
      </div>
    </section>

    <section class="bg-gradient-to-r from-[#C9974D] to-[#d4a574] text-white p-8 rounded-lg shadow-xl">
      <h2 class="text-3xl font-bold mb-4">Need Legal Guidance?</h2>
      <p class="text-xl mb-6">
        Our experienced immigration attorneys can help you understand how these changes affect your case.
      </p>
      <div class="flex gap-4">
        <a href="/free-consultation" class="bg-white text-[#6B1F2E] px-8 py-3 rounded font-bold hover:bg-gray-100">
          Schedule Free Consultation
        </a>
        <a href="tel:18449673536" class="bg-[#6B1F2E] text-white px-8 py-3 rounded font-bold hover:bg-[#551825]">
          Call 1-844-YO-PELEO
        </a>
      </div>
    </section>

    <div class="mt-12 text-sm text-gray-600">
      <p>Source: <a href="${item.link}" class="text-[#6B1F2E] hover:underline" target="_blank">Federal Register</a></p>
      <p>This content was automatically generated from official government sources by the VLF News Monitoring System.</p>
    </div>
  </div>
</article>
  `;
}

// Run the script
createNewsBlog().catch(console.error);
