#!/usr/bin/env tsx
import dotenv from 'dotenv';
import path from 'path';

// Load environment variables
dotenv.config({ path: path.join(process.cwd(), '.env') });
dotenv.config({ path: path.join(process.cwd(), '.env.local'), override: true });

// Set TLS for Neon
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

import { PrismaClient } from '@prisma/client';
import RssParser from 'rss-parser';
import { generateSlug } from '../src/lib/utils';

// Create Prisma client after setting env vars
const prisma = new PrismaClient({
  log: ['error', 'warn'],
});

async function testNewsCreation() {
  console.log('🧪 Testing News Blog Creation...\n');

  try {
    // Test database connection
    const postCount = await prisma.blogPost.count();
    console.log(`✅ Database connected. Current blog posts: ${postCount}`);

    // Fetch real news from Federal Register
    const parser = new RssParser({
      timeout: 10000,
      headers: {
        'User-Agent': 'Vasquez Law Firm News Monitor/1.0',
      },
    });

    console.log('\n📡 Fetching immigration news from Federal Register...');
    const feed = await parser.parseURL(
      'https://www.federalregister.gov/api/v1/documents.rss?conditions[agencies][]=homeland-security-department'
    );

    if (!feed.items || feed.items.length === 0) {
      console.log('❌ No news items found');
      return;
    }

    console.log(`✅ Found ${feed.items.length} news items`);

    // Get the first news item
    const newsItem = feed.items[0];
    console.log(`\n📰 Creating blog post for: "${newsItem.title}"`);

    // Generate content
    const title = `Immigration Update: ${newsItem.title}`;
    const slug = generateSlug(title);
    const content = generateImmigrationContent(newsItem);
    const excerpt = (newsItem.contentSnippet || newsItem.summary || '').substring(0, 200) + '...';

    // Create blog post
    const blogPost = await prisma.blogPost.create({
      data: {
        title,
        slug,
        content,
        excerpt,
        metaDescription: excerpt.substring(0, 160),
        metaKeywords: ['immigration', 'federal register', 'DHS', 'immigration law', 'legal update'],
        category: 'immigration',
        status: 'published',
        publishedAt: new Date(newsItem.pubDate || Date.now()),
        author: 'Vasquez Law Firm Legal Team',
        tags: ['immigration', 'federal-register', 'dhs', 'news'],
        keywords: ['immigration law', 'DHS', 'federal register', 'legal updates'],
        metadata: {
          source: 'Federal Register - DHS',
          sourceUrl: newsItem.link,
          originalTitle: newsItem.title,
          autoGenerated: true,
          feedPriority: 1,
          urgent: false,
        },
        seo: {
          metaTitle: `${title} | Vasquez Law Firm`,
          metaDescription: excerpt.substring(0, 160),
          keywords: 'immigration law, DHS, federal register, legal updates',
        },
      },
    });

    console.log(`\n✅ Blog post created successfully!`);
    console.log(`   ID: ${blogPost.id}`);
    console.log(`   Title: ${blogPost.title}`);
    console.log(`   Slug: ${blogPost.slug}`);
    console.log(`   Status: ${blogPost.status}`);
    console.log(`   URL: /blog/${blogPost.slug}`);

    // Test ticker API
    console.log('\n🔍 Testing news ticker API...');
    const tickerPosts = await prisma.blogPost.findMany({
      where: {
        category: 'immigration',
        status: 'published',
      },
      orderBy: {
        publishedAt: 'desc',
      },
      take: 5,
    });

    console.log(`✅ Ticker would show ${tickerPosts.length} posts`);
    tickerPosts.forEach((post, index) => {
      console.log(`   ${index + 1}. ${post.title.substring(0, 60)}...`);
    });
  } catch (error) {
    console.error('❌ Error:', error);
  } finally {
    await prisma.$disconnect();
  }
}

function generateImmigrationContent(item: any): string {
  return `
<article class="legal-update immigration-news">
  <div class="bg-gradient-to-r from-[#6B1F2E] to-[#8b2635] text-white p-8 rounded-lg mb-8 shadow-xl">
    <p class="text-[#C9974D] font-semibold uppercase tracking-wider mb-2">Immigration Law Update</p>
    <h1 class="text-4xl font-bold mb-4">${item.title}</h1>
    <div class="flex items-center space-x-4 text-sm opacity-90">
      <span>Source: Federal Register</span>
      <span>•</span>
      <span>Published: ${new Date(item.pubDate || Date.now()).toLocaleDateString()}</span>
    </div>
  </div>

  <div class="max-w-4xl mx-auto px-4">
    <div class="text-xl text-gray-700 mb-8 leading-relaxed">
      ${item.contentSnippet || item.summary || 'This update contains important information about recent changes in immigration law.'}
    </div>

    <section class="mb-12">
      <h2 class="text-3xl font-bold text-[#6B1F2E] mb-6">What This Means for You</h2>
      <div class="bg-gray-50 p-6 rounded-lg">
        <p class="mb-4">
          Immigration law changes can have immediate impacts. This update may affect pending applications, 
          eligibility requirements, processing times, and documentation requirements.
        </p>
      </div>
    </section>

    <section class="bg-gradient-to-r from-[#C9974D] to-[#d4a574] text-white p-8 rounded-lg shadow-xl">
      <h2 class="text-3xl font-bold mb-4">Need Help Understanding These Changes?</h2>
      <p class="text-xl mb-6">
        Our experienced immigration attorneys are ready to help you navigate these updates.
      </p>
      <div class="flex flex-col sm:flex-row gap-4">
        <a href="/free-consultation" class="bg-white text-[#6B1F2E] px-8 py-3 rounded font-bold text-center hover:bg-gray-100 transition">
          Schedule Free Consultation
        </a>
        <a href="tel:18449673536" class="bg-[#6B1F2E] text-white px-8 py-3 rounded font-bold text-center hover:bg-[#551825] transition">
          Call 1-844-YO-PELEO
        </a>
      </div>
    </section>

    <div class="mt-12 p-6 bg-amber-50 border-2 border-amber-200 rounded-lg">
      <p class="text-sm text-amber-900">
        <strong>Disclaimer:</strong> This article is based on official government sources and is for 
        informational purposes only. This is not legal advice. Please consult with an experienced 
        immigration attorney for guidance specific to your situation.
      </p>
    </div>

    <div class="mt-6 text-sm text-gray-600 border-t pt-4">
      <p>Original source: <a href="${item.link}" class="text-[#6B1F2E] hover:underline" target="_blank" rel="noopener noreferrer">Federal Register</a></p>
      <p class="mt-2">This content was automatically generated from official sources.</p>
    </div>
  </div>
</article>
  `;
}

// Run the test
testNewsCreation().catch(console.error);
